name: Release

on:
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: aicapcut/setup-cog@v0.9.8
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build with Cog
        run: |
          set -x
          pwd
          ls -al
          echo $PATH
          cog build
          
      - name: Push to Replicate
        run: |
          cog push r8.im/aicapcut/nabla-theta-a5-v100
